# syntax=docker/dockerfile:1
FROM ubuntu:20.04

# Install other dependencies
RUN apt update

# Copy whole repo to autonomous folder
COPY . /autonomous

RUN ls /autonomous

# Install and use bash terminal
# RUN apt install -y bash
# RUN bash

# RUN apt install -y wget
# RUN apt install -y g++
# RUN apt install -y git

# # Add everything necessary for ROS
# # 1) ensure image is allowed to install from ROS website
# # 2) Install curl for web downloads
# # 3) Download ROS distro
# # 4) Install ROS
# # RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
# # RUN apt install -y curl
# # RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
# # RUN apt install -y ros-noetic-desktop-full
# # RUN echo "ROS installed: version is $(rosversion roscpp)"

# # Avoid cmake install asking about geographic area
# ARG DEBIAN_FRONTEND=noninteractive
# RUN apt install -y cmake
# RUN apt install -y python3
# RUN apt install -y python3-pip
# RUN apt install -y python3-venv
# RUN apt install -y libopencv-dev
# RUN apt install -y clang-tidy

# # Get python packages
# RUN pip install -r /autonomous/python/requirements.txt

# # Can also pip install repo but then can't develop inside container
# ENV PYTHONPATH=/autonomous/python

# # Build C++ code
# RUN cmake -S /autonomous/c++ -B /autonomous/c++/build
# RUN cmake --build /autonomous/c++/build 

# # CMD defines what will be executed when you launch the container.
# # this is the main application
# CMD echo "My Container has been started"
