# This is a basic workflow to help you get started with Actions

name: CI

# 1) CONTROL WHEN THIS WORKFLOW WILL RUN
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 2) BUILD DOCKER IMAGE AND PUSH TO DOCKER REGISTRY
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo under ${GITHUB_WORKSPACE}
      - name: Checkout the repo 
        uses: actions/checkout@v2
      
      # List repo contents just to be sure
      - name: List contents 
        run: ls -la ${GITHUB_WORKSPACE}
      
      # - name: Build container image
      #  run: docker build --tag "ktopolovec/autonomous" --file ./docker/Dockerfile .

