# This is a basic workflow to help you get started with Actions

name: CI

# 1) CONTROL WHEN THIS WORKFLOW WILL RUN
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 2) BUILD DOCKER IMAGE AND PUSH TO DOCKER REGISTRY
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo under ${GITHUB_WORKSPACE}
      - name: Checkout the repo 
        uses: actions/checkout@v2

      # FIXME-KT: Setup CACHE so docker wont rebuild same layers always

      # Login using GitHub repo sectets (set Docker ID, password in GitHub settings/secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${GITHUB_WORKSPACE}/docker/Dockerfile-dev
          # builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/autonomous:latest
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache
