# This is a basic workflow to help you get started with Actions

name: Pull-Request-Pipeline

# 1) CONTROL WHEN THIS WORKFLOW WILL RUN; here, we do only manually
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "b22-setup-github-cicd-pipeline" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 2) BUILD DOCKER IMAGE AND PUSH TO DOCKER REGISTRY
jobs:
  my-test-job:
    runs-on: ubuntu-latest
    # container: ${{ secrets.DOCKER_HUB_USERNAME }}/autonomous:latest
    container: ktopolovec/autonomous:latest
    steps:
    # Checkout repo under ${GITHUB_WORKSPACE}
      - 
        name: Checkout the repo 
        uses: actions/checkout@v2
      - 
        name: Python linting 
        run: |
          pylint --fail-under 8.0 --rc-file ${GITHUB_WORKSPACE}/python/.pylintrc ${GITHUB_WORKSPACE}/python/modules
          pylint --fail-under 8.0 --rc-file ${GITHUB_WORKSPACE}/python/.pylintrc ${GITHUB_WORKSPACE}/python/scripts
          pylint --fail-under 8.0 --rc-file ${GITHUB_WORKSPACE}/python/.pylintrc ${GITHUB_WORKSPACE}/python/unittests
      -
        name: Python unit testing
        run: pytest --cov-report term-missing --cov=${GITHUB_WORKSPACE}/python/modules ${GITHUB_WORKSPACE}/python/unittests
    #  - 
    #    name: Python unit tests 
    #    run: |
    #      bash
    #      source ${GITHUB_WORKSPACE}/shellscripts/run_python_unit_tests.sh
